import { PrismaClient, RuleType, RuleOperator, ValueType, ScoreBucket } from '@prisma/client'
import * as bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

async function main() {
  console.log(' Seeding database...')

  //  INSTITUTIONS 
  console.log('   Seeding institutions...')
  const institutions = await Promise.all([
    prisma.institution.upsert({
      where: { code: 'ANNA_UNIV' },
      update: {},
      create: { name: 'Anna University', code: 'ANNA_UNIV', type: 'University', affiliation: 'UGC', is_recognized: true, state: 'Tamil Nadu', district: 'Chennai' },
    }),
    prisma.institution.upsert({
      where: { code: 'IIT_MADRAS' },
      update: {},
      create: { name: 'IIT Madras', code: 'IIT_MADRAS', type: 'University', affiliation: 'UGC', is_recognized: true, state: 'Tamil Nadu', district: 'Chennai' },
    }),
    prisma.institution.upsert({
      where: { code: 'GOVT_ARTS_CBE' },
      update: {},
      create: { name: 'Government Arts College Coimbatore', code: 'GOVT_ARTS_CBE', type: 'College', affiliation: 'State Board', is_recognized: true, state: 'Tamil Nadu', district: 'Coimbatore' },
    }),
    prisma.institution.upsert({
      where: { code: 'PSG_TECH' },
      update: {},
      create: { name: 'PSG College of Technology', code: 'PSG_TECH', type: 'College', affiliation: 'AICTE', is_recognized: true, state: 'Tamil Nadu', district: 'Coimbatore' },
    }),
    prisma.institution.upsert({
      where: { code: 'UNRECOGNIZED_TEST' },
      update: {},
      create: { name: 'Test Unrecognized College', code: 'UNRECOGNIZED_TEST', type: 'College', affiliation: 'None', is_recognized: false, state: 'Tamil Nadu', district: 'Chennai' },
    }),
    prisma.institution.upsert({
      where: { code: 'NIT_TRICHY' },
      update: {},
      create: { name: 'NIT Tiruchirappalli', code: 'NIT_TRICHY', type: 'University', affiliation: 'UGC', is_recognized: true, state: 'Tamil Nadu', district: 'Trichy' },
    }),
    prisma.institution.upsert({
      where: { code: 'COIMBATORE_INST_TECH' },
      update: {},
      create: { name: 'Coimbatore Institute of Technology', code: 'COIMBATORE_INST_TECH', type: 'College', affiliation: 'AICTE', is_recognized: true, state: 'Tamil Nadu', district: 'Coimbatore' },
    }),
    prisma.institution.upsert({
      where: { code: 'MADURAI_KAMARAJ' },
      update: {},
      create: { name: 'Madurai Kamaraj University', code: 'MADURAI_KAMARAJ', type: 'University', affiliation: 'UGC', is_recognized: true, state: 'Tamil Nadu', district: 'Madurai' },
    }),
    prisma.institution.upsert({
      where: { code: 'THIAGARAJAR_CE' },
      update: {},
      create: { name: 'Thiagarajar College of Engineering', code: 'THIAGARAJAR_CE', type: 'College', affiliation: 'AICTE', is_recognized: true, state: 'Tamil Nadu', district: 'Madurai' },
    }),
    prisma.institution.upsert({
      where: { code: 'KONGU_ENG' },
      update: {},
      create: { name: 'Kongu Engineering College', code: 'KONGU_ENG', type: 'College', affiliation: 'AICTE', is_recognized: true, state: 'Tamil Nadu', district: 'Erode' },
    }),
    prisma.institution.upsert({
      where: { code: 'SRMC' },
      update: {},
      create: { name: 'Sri Ramachandra Institute of Higher Education', code: 'SRMC', type: 'University', affiliation: 'UGC', is_recognized: true, state: 'Tamil Nadu', district: 'Chennai' },
    }),
    prisma.institution.upsert({
      where: { code: 'VIT_VELLORE' },
      update: {},
      create: { name: 'VIT University Vellore', code: 'VIT_VELLORE', type: 'University', affiliation: 'UGC', is_recognized: true, state: 'Tamil Nadu', district: 'Vellore' },
    }),
    prisma.institution.upsert({
      where: { code: 'SASTRA_UNIV' },
      update: {},
      create: { name: 'SASTRA Deemed University', code: 'SASTRA_UNIV', type: 'University', affiliation: 'UGC', is_recognized: true, state: 'Tamil Nadu', district: 'Thanjavur' },
    }),
    prisma.institution.upsert({
      where: { code: 'BHARATH_UNIV' },
      update: {},
      create: { name: 'Bharath Institute of Higher Education', code: 'BHARATH_UNIV', type: 'University', affiliation: 'UGC', is_recognized: true, state: 'Tamil Nadu', district: 'Chennai' },
    }),
    prisma.institution.upsert({
      where: { code: 'SONA_CE' },
      update: {},
      create: { name: 'Sona College of Technology', code: 'SONA_CE', type: 'College', affiliation: 'AICTE', is_recognized: true, state: 'Tamil Nadu', district: 'Salem' },
    }),
    prisma.institution.upsert({
      where: { code: 'KUMARAGURU_CE' },
      update: {},
      create: { name: 'Kumaraguru College of Technology', code: 'KUMARAGURU_CE', type: 'College', affiliation: 'AICTE', is_recognized: true, state: 'Tamil Nadu', district: 'Coimbatore' },
    }),
    prisma.institution.upsert({
      where: { code: 'GCE_SALEM' },
      update: {},
      create: { name: 'Government College of Engineering Salem', code: 'GCE_SALEM', type: 'College', affiliation: 'AICTE', is_recognized: true, state: 'Tamil Nadu', district: 'Salem' },
    }),
    prisma.institution.upsert({
      where: { code: 'GOVT_ARTS_TRICHY' },
      update: {},
      create: { name: 'Government Arts College Tiruchirappalli', code: 'GOVT_ARTS_TRICHY', type: 'College', affiliation: 'State Board', is_recognized: true, state: 'Tamil Nadu', district: 'Trichy' },
    }),
    prisma.institution.upsert({
      where: { code: 'GOVT_ARTS_MADURAI' },
      update: {},
      create: { name: 'Government Arts College Madurai', code: 'GOVT_ARTS_MADURAI', type: 'College', affiliation: 'State Board', is_recognized: true, state: 'Tamil Nadu', district: 'Madurai' },
    }),
    prisma.institution.upsert({
      where: { code: 'PRESIDENCY_COLLEGE' },
      update: {},
      create: { name: 'Presidency College Chennai', code: 'PRESIDENCY_COLLEGE', type: 'College', affiliation: 'State Board', is_recognized: true, state: 'Tamil Nadu', district: 'Chennai' },
    }),
  ])

  //  ADMIN USER 
  console.log('   Seeding admin user...')
  const adminPassword    = await bcrypt.hash('Admin@1234', 12)
  const verifierPassword = await bcrypt.hash('Verifier@1234', 12)
  await prisma.user.upsert({
    where: { email: 'admin@scholarship.org' },
    update: {},
    create: {
      email: 'admin@scholarship.org',
      password_hash: adminPassword,
      full_name: 'Super Admin',
      role: 'super_admin',
      is_active: true,
    },
  })

  //  VERIFIER USER 
  await prisma.user.upsert({
    where: { email: 'verifier@scholarship.org' },
    update: {},
    create: {
      email: 'verifier@scholarship.org',
      password_hash: verifierPassword,
      full_name: 'Field Verifier',
      role: 'verifier',
      is_active: true,
    },
  })

  //  ELIGIBILITY RULES  ALL 63 
  console.log('   Seeding 63 eligibility rules...')

  const rules = [
    //  DOMAIN A  ACADEMIC (merit bucket) 
    {
      rule_code: 'A-01', rule_name: 'HSC / 12th Marks', domain: 'A',
      rule_type: RuleType.SCORE, score_bucket: ScoreBucket.merit,
      condition_field: 'student_academic.hsc_percentage',
      operator: RuleOperator.SCALE,
      default_value: { type: 'proportional', max_pts: 25, divisor: 100 },
      value_type: ValueType.scale, score_pts: 25.00, sort_order: 10,
      rule_description: 'HSC/12th marks scaled proportionally: hsc_pct / 100  25. 90%  22.5pts, 55%  13.75pts.',
      on_pass_action: 'merit += hsc_pct / 100 * 25',
      on_fail_action: 'merit += 0',
      cross_references: 'A-02, A-03, H-01',
    },
    {
      rule_code: 'A-02', rule_name: 'UG Aggregate Percentage', domain: 'A',
      rule_type: RuleType.SCORE, score_bucket: ScoreBucket.merit,
      condition_field: 'student_academic.ug_aggregate_pct',
      operator: RuleOperator.SCALE,
      default_value: { type: 'proportional', max_pts: 35, divisor: 100 },
      value_type: ValueType.scale, score_pts: 35.00, sort_order: 20,
      rule_description: 'UG aggregate scaled proportionally: ug_pct / 100  35. Largest single merit contributor.',
      on_pass_action: 'merit += ug_pct / 100 * 35',
      on_fail_action: 'merit += 0 (if no UG data, skip)',
      cross_references: 'A-01, A-03, H-01',
    },
    {
      rule_code: 'A-03', rule_name: 'Arrears Penalty', domain: 'A',
      rule_type: RuleType.SCORE, score_bucket: ScoreBucket.merit,
      condition_field: 'student_academic.active_arrears',
      operator: RuleOperator.FORMULA,
      // Cap changed from -30 to -15: a -30 swing is too aggressive in a scoring model and
      // can unfairly drop a high-need student below a clean-academic low-need student.
      // 3 arrears  -5 = -15 is the new hard floor (industry practice: binary or capped at -10/-15).
      default_value: { type: 'penalty_per_unit', pts_per_unit: -5, min_total: -15 },
      value_type: ValueType.number, score_pts: -15.00, sort_order: 30,
      rule_description: 'Each active arrear deducts 5 pts from merit. Capped at 15 pts (3 arrears). A 30 swing was too aggressive  a high-need student with arrears should not fall below a low-need clean-record student. Configurable via program_rule_overrides.',
      on_pass_action: 'merit += max(active_arrears * -5, -15)',
      on_fail_action: 'merit += 0 (no arrears)',
      cross_references: 'A-01, A-02',
    },
    {
      rule_code: 'A-04', rule_name: 'Full-Time Study Mode', domain: 'A',
      rule_type: RuleType.SCORE, score_bucket: ScoreBucket.merit,
      condition_field: 'student_academic.study_mode',
      operator: RuleOperator.EQ,
      default_value: { value: 'full_time' },
      value_type: ValueType.string, score_pts: 5.00, sort_order: 40,
      rule_description: 'Full-time students receive +5 pts. Part-time/distance students receive 0.',
      on_pass_action: 'merit += 5',
      on_fail_action: 'merit += 0',
      cross_references: 'A-05, A-10',
    },
    {
      rule_code: 'A-05', rule_name: 'Approved Course Type', domain: 'A',
      rule_type: RuleType.SCORE, score_bucket: ScoreBucket.merit,
      condition_field: 'student_academic.course_type',
      operator: RuleOperator.IN,
      default_value: { values: ['engineering', 'medicine', 'law', 'arts_science', 'management', 'other'] },
      value_type: ValueType.json_array, score_pts: 5.00, sort_order: 50,
      rule_description: 'Course type must be in program-approved UG list. Configurable per program via overrides.',
      on_pass_action: 'merit += 5',
      on_fail_action: 'merit += 0',
      cross_references: 'A-04, A-09',
    },
    {
      rule_code: 'A-06', rule_name: 'First-Generation Graduate', domain: 'A',
      rule_type: RuleType.SCORE, score_bucket: ScoreBucket.merit,
      condition_field: 'student_personal.is_first_graduate',
      operator: RuleOperator.EQ,
      default_value: { value: true },
      value_type: ValueType.boolean, score_pts: 10.00, sort_order: 60,
      rule_description: 'First person in family to attend college. Strong need indicator. +10 pts.',
      on_pass_action: 'merit += 10',
      on_fail_action: 'merit += 0',
      cross_references: 'B-03, F-02, F-05',
    },
    {
      rule_code: 'A-07', rule_name: 'No Other Active Scholarship', domain: 'A',
      rule_type: RuleType.SCORE, score_bucket: ScoreBucket.merit,
      condition_field: 'student_academic.receiving_other_scholarship',
      operator: RuleOperator.EQ,
      default_value: { value: false },
      value_type: ValueType.boolean, score_pts: 10.00, sort_order: 70,
      rule_description: 'Not currently receiving another scholarship. Prevents double funding. +10 pts.',
      on_pass_action: 'merit += 10',
      on_fail_action: 'merit += 0',
      cross_references: 'A-08',
    },
    {
      rule_code: 'A-08', rule_name: 'No Prior Trust Award', domain: 'A',
      rule_type: RuleType.SCORE, score_bucket: ScoreBucket.merit,
      condition_field: 'student_academic.prev_awarded_by_trust',
      operator: RuleOperator.EQ,
      default_value: { value: false },
      value_type: ValueType.boolean, score_pts: 5.00, sort_order: 80,
      rule_description: 'Not previously awarded by this specific trust. Promotes fresh beneficiaries.',
      on_pass_action: 'merit += 5',
      on_fail_action: 'merit += 0',
      cross_references: 'A-07',
    },
    {
      rule_code: 'A-09', rule_name: 'Recognized Institution', domain: 'A',
      rule_type: RuleType.SCORE, score_bucket: ScoreBucket.merit,
      condition_field: 'institution.is_recognized',
      operator: RuleOperator.EQ,
      default_value: { value: true },
      value_type: ValueType.boolean, score_pts: 5.00, sort_order: 90,
      is_active: false,
      rule_description: 'Deactivated — institution validation removed. Any institution accepted.',
      on_pass_action: 'merit += 5',
      on_fail_action: 'merit += 0',
      cross_references: 'A-05',
    },
    {
      rule_code: 'A-10', rule_name: 'Currently Enrolled', domain: 'A',
      rule_type: RuleType.SCORE, score_bucket: ScoreBucket.merit,
      condition_field: 'student_personal.enrollment_status',
      operator: RuleOperator.EQ,
      default_value: { value: 'active' },
      value_type: ValueType.string, score_pts: 2.00, sort_order: 100,
      rule_description: 'Student must be actively enrolled. +2 pts. Inactive/on-leave = 0.',
      on_pass_action: 'merit += 2',
      on_fail_action: 'merit += 0',
      cross_references: 'A-04',
    },

    //  DOMAIN B  INCOME (need bucket) 
    {
      rule_code: 'B-01', rule_name: 'Annual Family Income (Inverse Scale)', domain: 'B',
      rule_type: RuleType.SCORE, score_bucket: ScoreBucket.need,
      condition_field: 'student_financial.total_annual_income',
      operator: RuleOperator.SCALE,
      default_value: {
        type: 'step_scale',
        steps: [
          { lte: 100000,  pts: 30 },
          { lte: 200000,  pts: 25 },
          { lte: 300000,  pts: 20 },
          { lte: 400000,  pts: 15 },
          { lte: 600000,  pts: 8  },
          { lte: 800000,  pts: 3  },
          { gt:  800000,  pts: 0  },
        ],
      },
      value_type: ValueType.scale, score_pts: 30.00, sort_order: 110,
      rule_description: 'Core income scoring. Inverse scale  lower income = higher need score. Primary driver of need bucket.',
      on_pass_action: 'need += pts from scale step',
      on_fail_action: 'need += 0 (income > 8L)',
      cross_references: 'B-02, D-01, E-01, G-01..G-07',
    },
    {
      rule_code: 'B-02', rule_name: 'Per-Capita Income Bonus', domain: 'B',
      rule_type: RuleType.SCORE, score_bucket: ScoreBucket.need,
      condition_field: 'student_financial.total_annual_income',
      condition_field_2: 'student_family.family_size',
      operator: RuleOperator.FORMULA,
      default_value: {
        type: 'per_capita_scale',
        formula: 'income / family_size',
        steps: [
          { lte: 40000,  pts: 5 },
          { lte: 80000,  pts: 3 },
          { lte: 120000, pts: 1 },
          { gt:  120000, pts: 0 },
        ],
      },
      value_type: ValueType.scale, score_pts: 5.00, sort_order: 120,
      rule_description: 'Per-capita income = total_income / family_size. Rewards larger families with lower per-person income.',
      on_pass_action: 'need += pts from per-capita step',
      on_fail_action: 'need += 0',
      cross_references: 'B-01, C-01',
    },
    {
      rule_code: 'B-03', rule_name: 'BPL / AAY Ration Card', domain: 'B',
      rule_type: RuleType.SCORE, score_bucket: ScoreBucket.need,
      condition_field: 'student_financial.ration_card_type',
      operator: RuleOperator.IN,
      default_value: { values: ['BPL', 'AAY'] },
      value_type: ValueType.json_array, score_pts: 3.00, sort_order: 130,
      rule_description: 'Government-certified BPL or AAY ration card. Strongest official poverty certification. +3 pts.',
      on_pass_action: 'need += 3',
      on_fail_action: 'need += 0',
      cross_references: 'B-01, F-01, A-06',
    },
    {
      rule_code: 'B-04', rule_name: 'Loan Burden Bonus', domain: 'B',
      rule_type: RuleType.SCORE, score_bucket: ScoreBucket.need,
      condition_field: 'student_financial.loan_outstanding',
      condition_field_2: 'student_financial.total_annual_income',
      operator: RuleOperator.FORMULA,
      default_value: {
        type: 'ratio_scale',
        formula: 'loan_outstanding / total_annual_income',
        steps: [
          { gt: 0.5,  pts: 2 },
          { gte: 0.25, lte: 0.5, pts: 1 },
          { lt: 0.25,  pts: 0 },
        ],
      },
      value_type: ValueType.scale, score_pts: 2.00, sort_order: 140,
      rule_description: 'Loan repayment burden as % of income. >50% = +2pts, 25-50% = +1pt. Rewards high debt burden.',
      on_pass_action: 'need += pts from ratio step',
      on_fail_action: 'need += 0',
      cross_references: 'B-01, C-01',
    },

    //  DOMAIN C  FAMILY (need bucket) 
    {
      rule_code: 'C-01', rule_name: 'Family Composition Score', domain: 'C',
      rule_type: RuleType.SCORE, score_bucket: ScoreBucket.need,
      condition_field: 'student_family.family_size',
      operator: RuleOperator.FORMULA,
      default_value: {
        type: 'composite_sub_rules',
        max_pts: 9,
        sub_rules: [
          { field: 'family_size',         gte: 6,    pts: 2 },
          { field: 'earning_members',     lte: 1,    pts: 2 },
          { field: 'dependents',          gte: 4,    pts: 2 },
          { field: 'siblings_in_education', gte: 3,  pts: 2 },
          { field: 'has_chronic_illness', eq: true,  pts: 1 },
        ],
      },
      value_type: ValueType.scale, score_pts: 9.00, sort_order: 150,
      rule_description: 'Composite family vulnerability: large family (+2), single earner (+2), many dependents (+2), siblings in edu (+2), chronic illness (+1). Cap 9 pts.',
      on_pass_action: 'need += sum of sub-rule pts (max 9)',
      on_fail_action: 'need += 0 per unmet sub-rule',
      cross_references: 'B-02, E-04, B-04',
    },
    {
      rule_code: 'C-02', rule_name: 'Single Earner + High Dependents', domain: 'C',
      rule_type: RuleType.SCORE, score_bucket: ScoreBucket.need,
      condition_field: 'student_family.earning_members',
      condition_field_2: 'student_family.dependents',
      operator: RuleOperator.AND_COMPOUND,
      default_value: { field1_eq: 1, field2_gte: 4 },
      value_type: ValueType.number, score_pts: 3.00, sort_order: 160,
      rule_description: 'Exactly 1 earning member AND 4+ dependents  extreme burden. +3 pts.',
      on_pass_action: 'need += 3',
      on_fail_action: 'need += 0',
      cross_references: 'C-01, B-01',
    },
    {
      rule_code: 'C-03', rule_name: 'Orphan Status', domain: 'C',
      rule_type: RuleType.SCORE, score_bucket: ScoreBucket.need,
      condition_field: 'student_personal.father_status',
      condition_field_2: 'student_personal.mother_status',
      operator: RuleOperator.FORMULA,
      default_value: {
        type: 'dual_status',
        both_deceased: 5,
        one_deceased: 3,
        both_alive: 0,
      },
      value_type: ValueType.scale, score_pts: 5.00, sort_order: 170,
      rule_description: 'Both parents deceased = +5 pts (orphan). One parent deceased = +3 pts. Unlocks C-06 guardian income check.',
      on_pass_action: 'need += 5 (both) or 3 (one)',
      on_fail_action: 'need += 0',
      cross_references: 'C-04, C-06, F-05',
    },
    {
      rule_code: 'C-04', rule_name: 'Single Parent Family', domain: 'C',
      rule_type: RuleType.SCORE, score_bucket: ScoreBucket.need,
      condition_field: 'student_personal.is_single_parent',
      operator: RuleOperator.EQ,
      default_value: { value: true },
      value_type: ValueType.boolean, score_pts: 3.00, sort_order: 180,
      rule_description: 'Single parent household. +3 pts.',
      on_pass_action: 'need += 3',
      on_fail_action: 'need += 0',
      cross_references: 'C-03, C-01, F-05, F-07',
    },
    {
      rule_code: 'C-05', rule_name: 'Chronic Illness in Family', domain: 'C',
      rule_type: RuleType.SCORE, score_bucket: ScoreBucket.need,
      condition_field: 'student_family.has_chronic_illness',
      operator: RuleOperator.EQ,
      default_value: { value: true },
      value_type: ValueType.boolean, score_pts: 2.00, sort_order: 190,
      rule_description: 'Family member with chronic illness (cancer, kidney failure, etc.) creates ongoing financial drain. +2 pts.',
      on_pass_action: 'need += 2',
      on_fail_action: 'need += 0',
      cross_references: 'C-01, B-01',
    },
    {
      rule_code: 'C-06', rule_name: 'Guardian Annual Income (Orphan Conditional)', domain: 'C',
      rule_type: RuleType.SCORE, score_bucket: ScoreBucket.need,
      condition_field: 'student_personal.guardian_annual_income',
      operator: RuleOperator.SCALE,
      default_value: {
        type: 'conditional_scale',
        condition: 'student_personal.is_orphan == true',
        steps: [
          { lte: 100000, pts: 3 },
          { lte: 300000, pts: 2 },
          { lte: 500000, pts: 1 },
          { gt:  500000, pts: 0 },
        ],
      },
      value_type: ValueType.scale, score_pts: 3.00, sort_order: 200,
      rule_description: 'Only applies if C-03 confirms orphan status. Scores guardian income on inverse scale.',
      on_pass_action: 'need += pts from guardian income scale',
      on_fail_action: 'need += 0 (skip if not orphan)',
      cross_references: 'C-03',
    },

    //  DOMAIN D  ASSETS (need bucket) 
    {
      rule_code: 'D-01', rule_name: 'Total Asset Value (Inverse Scale)', domain: 'D',
      rule_type: RuleType.SCORE, score_bucket: ScoreBucket.need,
      condition_field: 'student_assets.total_asset_value',
      operator: RuleOperator.SCALE,
      default_value: {
        type: 'step_scale',
        steps: [
          { lte: 50000,  pts: 8 },
          { lte: 100000, pts: 6 },
          { lte: 300000, pts: 3 },
          { lte: 500000, pts: 1 },
          { gt:  500000, pts: 0 },
        ],
      },
      value_type: ValueType.scale, score_pts: 8.00, sort_order: 210,
      rule_description: 'Total declared asset value. Inverse  fewer assets = higher need. 50K = 8pts, >5L = 0pts.',
      on_pass_action: 'need += pts from asset scale',
      on_fail_action: 'need += 0',
      cross_references: 'B-01, E-01, G-01..G-05',
    },
    {
      rule_code: 'D-02', rule_name: 'Land Ownership Adjustment', domain: 'D',
      rule_type: RuleType.SCORE, score_bucket: ScoreBucket.need,
      condition_field: 'student_assets.land_area_acres',
      operator: RuleOperator.SCALE,
      default_value: {
        type: 'step_scale',
        steps: [
          { eq: 0,            pts: 3  },
          { gt: 0, lt: 1,     pts: 1  },
          { gte: 1, lte: 3,   pts: 0  },
          { gt: 3,            pts: -2 },
        ],
      },
      value_type: ValueType.scale, score_pts: 3.00, sort_order: 220,
      rule_description: 'No land = +3, small land = +1, medium = 0, large landowner >3 acres = 2. Negative score possible here.',
      on_pass_action: 'need += pts from land scale',
      on_fail_action: 'n/a (always applies)',
      cross_references: 'E-03, B-01',
    },
    {
      rule_code: 'D-03', rule_name: 'No Vehicle Bonus', domain: 'D',
      rule_type: RuleType.SCORE, score_bucket: ScoreBucket.need,
      condition_field: 'student_assets.vehicle_count',
      operator: RuleOperator.EQ,
      default_value: { value: 0 },
      value_type: ValueType.number, score_pts: 2.00, sort_order: 230,
      rule_description: 'No vehicles at all = +2 pts. Note: G-01 specifically checks car_value  3L as fraud signal.',
      on_pass_action: 'need += 2',
      on_fail_action: 'need += 0',
      cross_references: 'B-01, G-01',
    },
    {
      rule_code: 'D-04', rule_name: 'Gold / Jewellery Value', domain: 'D',
      rule_type: RuleType.SCORE, score_bucket: ScoreBucket.need,
      condition_field: 'student_financial.gold_value_inr',
      operator: RuleOperator.LT,
      default_value: { value: 200000 },
      value_type: ValueType.number, score_pts: 2.00, sort_order: 240,
      rule_description: 'Gold < 2L = +2 pts. Gold is a major stored-wealth indicator in Indian households. 2L = 0 (and G-03 deducts).',
      on_pass_action: 'need += 2',
      on_fail_action: 'need += 0',
      cross_references: 'B-01, G-03',
    },
    {
      rule_code: 'D-05', rule_name: 'Fixed Deposits / Savings', domain: 'D',
      rule_type: RuleType.SCORE, score_bucket: ScoreBucket.need,
      condition_field: 'student_financial.fixed_deposit_amount',
      operator: RuleOperator.SCALE,
      default_value: {
        type: 'step_scale',
        steps: [
          { eq: 0,          pts: 2 },
          { gt: 0, lt: 100000, pts: 1 },
          { gte: 100000,    pts: 0 },
        ],
      },
      value_type: ValueType.scale, score_pts: 2.00, sort_order: 250,
      rule_description: 'No FD = +2, small FD <1L = +1, FD 1L = 0 (G-04 deducts for 2L FD alongside low income).',
      on_pass_action: 'need += pts from FD scale',
      on_fail_action: 'need += 0',
      cross_references: 'B-01, G-04',
    },

    //  DOMAIN E  HOUSING (need bucket) 
    {
      rule_code: 'E-01', rule_name: 'Housing Type (Census Classification)', domain: 'E',
      rule_type: RuleType.SCORE, score_bucket: ScoreBucket.need,
      condition_field: 'student_housing.house_type',
      operator: RuleOperator.SCALE,
      default_value: {
        type: 'enum_scale',
        values: {
          kuccha: 10, semi_pucca: 6, pucca_rented: 3,
          pucca_owned: 1, flat_apartment: 0, homeless: 10,
        },
      },
      value_type: ValueType.scale, score_pts: 10.00, sort_order: 260,
      rule_description: 'Census-aligned housing classification. Kuccha (mud/thatch) = 10pts  single strongest poverty indicator. Homeless = 10pts.',
      on_pass_action: 'need += pts from enum map',
      on_fail_action: 'need += 0 (flat)',
      cross_references: 'B-01, D-01, G-05',
    },
    {
      rule_code: 'E-02', rule_name: 'Utilities Deprivation Score', domain: 'E',
      rule_type: RuleType.SCORE, score_bucket: ScoreBucket.need,
      condition_field: 'student_housing.has_electricity',
      operator: RuleOperator.FORMULA,
      default_value: {
        type: 'multi_boolean',
        items: [
          { field: 'has_electricity', eq: false, pts: 1.5 },
          { field: 'has_piped_water', eq: false, pts: 1.5 },
          { field: 'has_toilet',      eq: false, pts: 1.5 },
          { field: 'has_lpg',         eq: false, pts: 0.5 },
        ],
        max_pts: 5,
      },
      value_type: ValueType.scale, score_pts: 5.00, sort_order: 270,
      rule_description: 'Each missing utility adds deprivation points. No electricity/water/toilet = 1.5 each, no LPG = 0.5. Max 5 pts.',
      on_pass_action: 'need += sum of utility deprivation pts (max 5)',
      on_fail_action: 'need += 0 per available utility',
      cross_references: 'E-01',
    },
    {
      rule_code: 'E-03', rule_name: 'Housing Ownership Type', domain: 'E',
      rule_type: RuleType.SCORE, score_bucket: ScoreBucket.need,
      condition_field: 'student_housing.ownership_type',
      operator: RuleOperator.SCALE,
      default_value: {
        type: 'enum_scale',
        values: { homeless: 4, rented: 2, govt_allotted: 1, owned: 0 },
      },
      value_type: ValueType.scale, score_pts: 4.00, sort_order: 280,
      rule_description: 'Homeless = +4, rented = +2, govt-allotted = +1, owned = 0.',
      on_pass_action: 'need += pts from ownership enum',
      on_fail_action: 'need += 0 (owned)',
      cross_references: 'E-01, B-01',
    },
    {
      rule_code: 'E-04', rule_name: 'Overcrowding Ratio', domain: 'E',
      rule_type: RuleType.SCORE, score_bucket: ScoreBucket.need,
      condition_field: 'student_housing.total_rooms',
      condition_field_2: 'student_family.family_size',
      operator: RuleOperator.FORMULA,
      default_value: { type: 'ratio_lt', formula: 'total_rooms / family_size', threshold: 0.5, pts: 2 },
      value_type: ValueType.number, score_pts: 2.00, sort_order: 290,
      rule_description: 'Rooms per person < 0.5 (severe overcrowding) = +2 pts. E.g. 2 rooms for 5 people.',
      on_pass_action: 'need += 2',
      on_fail_action: 'need += 0',
      cross_references: 'C-01, E-01',
    },
    {
      rule_code: 'E-05', rule_name: 'Rural / Tribal Location', domain: 'E',
      rule_type: RuleType.SCORE, score_bucket: ScoreBucket.need,
      condition_field: 'student_personal.residential_type',
      operator: RuleOperator.IN,
      default_value: { values: ['rural', 'tribal'] },
      value_type: ValueType.json_array, score_pts: 2.00, sort_order: 300,
      rule_description: 'Rural or tribal area residence = +2 pts. Reflects access disadvantage.',
      on_pass_action: 'need += 2',
      on_fail_action: 'need += 0 (urban)',
      cross_references: 'E-01, B-01',
    },

    //  DOMAIN F  SOCIAL / VULNERABILITY (need bucket) 
    {
      rule_code: 'F-01', rule_name: 'Government Benefits Score', domain: 'F',
      rule_type: RuleType.SCORE, score_bucket: ScoreBucket.need,
      condition_field: 'student_govt_benefits.has_active_benefits',
      operator: RuleOperator.FORMULA,
      default_value: {
        type: 'multi_boolean',
        items: [
          { field: 'has_bpl_card',    eq: true, pts: 2   },
          { field: 'has_aay_card',    eq: true, pts: 2   },
          { field: 'has_mgnrega',     eq: true, pts: 1.5 },
          { field: 'has_ayushman',    eq: true, pts: 1   },
          { field: 'has_pm_schemes',  eq: true, pts: 1.5 },
        ],
        max_pts: 8,
      },
      value_type: ValueType.scale, score_pts: 8.00, sort_order: 310,
      rule_description: 'BPL card +2, AAY +2, MGNREGA +1.5, Ayushman Bharat +1, PM schemes +1.5. Max 8 pts. Official poverty certificates.',
      on_pass_action: 'need += sum of benefit pts (max 8)',
      on_fail_action: 'need += 0',
      cross_references: 'B-03, F-06, G-07',
    },
    {
      // F-02 DEACTIVATED (is_active: false)  vulnerability scoring for disability is now
      // consolidated in F-05 (Vulnerability Composite). Keeping F-02 active alongside F-05
      // causes double-counting: a disabled SC student scores +6 (F-02) + +3 (F-03) + up to +6+3
      // again inside F-05, before F-05's 15-pt cap kicks in. Real trusts use F-05 as the sole
      // vulnerability scorer. F-02 is retained in the DB for audit/reference and can be
      // re-activated (with F-05 deactivated) via program_rule_overrides if a program prefers
      // flat per-category bonuses over the composite model.
      rule_code: 'F-02', rule_name: 'Disability Bonus (Standalone  use F-05)', domain: 'F',
      rule_type: RuleType.SCORE, score_bucket: ScoreBucket.need,
      condition_field: 'student_personal.is_differently_abled',
      operator: RuleOperator.EQ,
      default_value: { value: true },
      value_type: ValueType.boolean, score_pts: 6.00, sort_order: 320,
      is_active: false,
      rule_description: 'DEACTIVATED  disability scoring consolidated into F-05 Vulnerability Composite to eliminate double-counting. Re-activate via program_rule_overrides if using flat-bonus model (then deactivate F-05). J-06 award uplift still fires independently.',
      on_pass_action: 'need += 6 (when active)',
      on_fail_action: 'need += 0',
      cross_references: 'F-05, J-06',
    },
    {
      // F-03 DEACTIVATED  see F-02 comment. SC/ST scoring now solely via F-05 sub-rule.
      rule_code: 'F-03', rule_name: 'SC / ST Caste Bonus (Standalone  use F-05)', domain: 'F',
      rule_type: RuleType.SCORE, score_bucket: ScoreBucket.need,
      condition_field: 'student_personal.caste_category',
      operator: RuleOperator.IN,
      default_value: { values: ['SC', 'ST'] },
      value_type: ValueType.json_array, score_pts: 3.00, sort_order: 330,
      is_active: false,
      rule_description: 'DEACTIVATED  SC/ST scoring consolidated into F-05 Vulnerability Composite to eliminate double-counting. Re-activate via program_rule_overrides for flat-bonus model.',
      on_pass_action: 'need += 3 (when active)',
      on_fail_action: 'need += 0',
      cross_references: 'F-05',
    },
    {
      // F-04 DEACTIVATED  see F-02 comment. Minority scoring now solely via F-05 sub-rule.
      rule_code: 'F-04', rule_name: 'Religious Minority Bonus (Standalone  use F-05)', domain: 'F',
      rule_type: RuleType.SCORE, score_bucket: ScoreBucket.need,
      condition_field: 'student_personal.religion_minority_status',
      operator: RuleOperator.EQ,
      default_value: { value: true },
      value_type: ValueType.boolean, score_pts: 2.00, sort_order: 340,
      is_active: false,
      rule_description: 'DEACTIVATED  minority scoring consolidated into F-05 Vulnerability Composite to eliminate double-counting. Re-activate via program_rule_overrides for flat-bonus model.',
      on_pass_action: 'need += 2 (when active)',
      on_fail_action: 'need += 0',
      cross_references: 'F-05',
    },
    {
      // F-05 is now THE sole vulnerability scorer for disability, SC/ST, minority, orphan,
      // single-parent, and widow. F-02, F-03, F-04 are deactivated above. The 15-pt cap
      // prevents any single student from accumulating runaway vulnerability points.
      rule_code: 'F-05', rule_name: 'Vulnerability Composite (Sole Aggregator)', domain: 'F',
      rule_type: RuleType.SCORE, score_bucket: ScoreBucket.need,
      condition_field: 'student_personal.is_differently_abled',
      operator: RuleOperator.FORMULA,
      default_value: {
        type: 'composite_aggregator',
        max_pts: 15,
        sub_rules: [
          { field: 'is_differently_abled',     eq: true,         pts: 6 },
          { field: 'is_orphan',                eq: true,         pts: 5 },
          { field: 'is_single_parent',         eq: true,         pts: 3 },
          { field: 'caste_category',           in: ['SC', 'ST'], pts: 3 },
          { field: 'religion_minority_status', eq: true,         pts: 2 },
          { field: 'mother_widow_pension',     eq: true,         pts: 2 },
        ],
      },
      value_type: ValueType.scale, score_pts: 15.00, sort_order: 350,
      rule_description: 'SOLE vulnerability scorer (F-02, F-03, F-04 deactivated). Scores disability (+6), orphan (+5), single-parent (+3), SC/ST (+3), religious minority (+2), widow pension (+2). Capped at 15 pts. A disabled SC orphan cannot exceed 15 pts regardless of how many axes apply, eliminating double-counting.',
      on_pass_action: 'need += sum of sub-rule pts (max 15)',
      on_fail_action: 'need += 0',
      cross_references: 'C-03, C-04, F-02, F-03, F-04, F-07',
    },
    {
      rule_code: 'F-06', rule_name: 'BPL Income + No Benefits (Welfare Gap)', domain: 'F',
      rule_type: RuleType.SCORE, score_bucket: ScoreBucket.need,
      condition_field: 'student_financial.total_annual_income',
      condition_field_2: 'student_govt_benefits.has_active_benefits',
      operator: RuleOperator.AND_COMPOUND,
      default_value: { field1_lte: 72000, field2_eq: false },
      value_type: ValueType.number, score_pts: 2.00, sort_order: 360,
      rule_description: 'Income  72K (below BPL line) AND no active benefits = +2 pts. Catches genuinely poor families not enrolled in welfare schemes.',
      on_pass_action: 'need += 2',
      on_fail_action: 'need += 0',
      cross_references: 'F-01, B-03',
    },
    {
      rule_code: 'F-07', rule_name: 'Widow Parent Pension', domain: 'F',
      rule_type: RuleType.SCORE, score_bucket: ScoreBucket.need,
      condition_field: 'student_family.mother_widow_pension',
      operator: RuleOperator.EQ,
      default_value: { value: true },
      value_type: ValueType.boolean, score_pts: 2.00, sort_order: 370,
      rule_description: 'Mother receiving widow pension = +2 pts. Indicates single-income vulnerable household.',
      on_pass_action: 'need += 2',
      on_fail_action: 'need += 0',
      cross_references: 'C-04, F-05',
    },

    //  DOMAIN G  INTEGRITY DEDUCTIONS 
    {
      rule_code: 'G-01', rule_name: 'Low Income + High-Value Vehicle', domain: 'G',
      rule_type: RuleType.DEDUCTION, score_bucket: ScoreBucket.integrity,
      condition_field: 'student_financial.total_annual_income',
      condition_field_2: 'student_assets.car_value',
      operator: RuleOperator.AND_COMPOUND,
      default_value: { field1_lte: 200000, field2_gte: 300000 },
      value_type: ValueType.number, score_pts: -8.00, sort_order: 380,
      rule_description: 'Income  2L AND car_value  3L. Strongest fraud signal. 8 pts. Two-wheelers < 50K excluded.',
      on_pass_action: 'integrity_adj += -8',
      on_fail_action: 'integrity_adj += 0',
      cross_references: 'B-01, D-03',
    },
    {
      rule_code: 'G-02', rule_name: 'Low Income + High Electronics', domain: 'G',
      rule_type: RuleType.DEDUCTION, score_bucket: ScoreBucket.integrity,
      condition_field: 'student_financial.total_annual_income',
      condition_field_2: 'student_assets.electronics_value',
      operator: RuleOperator.AND_COMPOUND,
      default_value: { field1_lte: 200000, field2_gte: 50000 },
      value_type: ValueType.number, score_pts: -5.00, sort_order: 390,
      rule_description: 'Income  2L AND electronics  50K (ACs, smart TVs, computers). 5 pts.',
      on_pass_action: 'integrity_adj += -5',
      on_fail_action: 'integrity_adj += 0',
      cross_references: 'B-01, D-01',
    },
    {
      rule_code: 'G-03', rule_name: 'Low Income + High Gold Holdings', domain: 'G',
      rule_type: RuleType.DEDUCTION, score_bucket: ScoreBucket.integrity,
      condition_field: 'student_financial.total_annual_income',
      condition_field_2: 'student_financial.gold_value_inr',
      operator: RuleOperator.AND_COMPOUND,
      default_value: { field1_lte: 200000, field2_gte: 200000 },
      value_type: ValueType.number, score_pts: -6.00, sort_order: 400,
      rule_description: 'Income  2L AND gold  2L. Gold is stored wealth in India. 6 pts.',
      on_pass_action: 'integrity_adj += -6',
      on_fail_action: 'integrity_adj += 0',
      cross_references: 'B-01, D-04',
    },
    {
      rule_code: 'G-04', rule_name: 'Low Income + Fixed Deposits', domain: 'G',
      rule_type: RuleType.DEDUCTION, score_bucket: ScoreBucket.integrity,
      condition_field: 'student_financial.total_annual_income',
      condition_field_2: 'student_financial.fixed_deposit_amount',
      operator: RuleOperator.AND_COMPOUND,
      default_value: { field1_lte: 200000, field2_gte: 100000 },
      value_type: ValueType.number, score_pts: -8.00, sort_order: 410,
      rule_description: 'Income  2L AND FD  1L. Strongest bank fraud signal. 8 pts.',
      on_pass_action: 'integrity_adj += -8',
      on_fail_action: 'integrity_adj += 0',
      cross_references: 'B-01, D-05',
    },
    {
      rule_code: 'G-05', rule_name: 'Kuccha House + High Assets', domain: 'G',
      rule_type: RuleType.DEDUCTION, score_bucket: ScoreBucket.integrity,
      condition_field: 'student_housing.house_type',
      condition_field_2: 'student_assets.total_asset_value',
      operator: RuleOperator.AND_COMPOUND,
      default_value: { field1_eq: 'kuccha', field2_gte: 100000 },
      value_type: ValueType.number, score_pts: -6.00, sort_order: 420,
      rule_description: 'Kuccha house declared but assets  1L. Housing/asset contradiction. 6 pts.',
      on_pass_action: 'integrity_adj += -6',
      on_fail_action: 'integrity_adj += 0',
      cross_references: 'E-01, D-01',
    },
    {
      rule_code: 'G-06', rule_name: 'Rented Housing + Land Ownership', domain: 'G',
      rule_type: RuleType.DEDUCTION, score_bucket: ScoreBucket.integrity,
      condition_field: 'student_housing.ownership_type',
      condition_field_2: 'student_assets.owns_land',
      operator: RuleOperator.AND_COMPOUND,
      default_value: { field1_eq: 'rented', field2_eq: true },
      value_type: ValueType.number, score_pts: -4.00, sort_order: 430,
      rule_description: 'Paying rent while owning land suggests under-reported land assets. 4 pts.',
      on_pass_action: 'integrity_adj += -4',
      on_fail_action: 'integrity_adj += 0',
      cross_references: 'E-03, D-02',
    },
    {
      rule_code: 'G-07', rule_name: 'Benefits + High Income Contradiction', domain: 'G',
      rule_type: RuleType.DEDUCTION, score_bucket: ScoreBucket.integrity,
      condition_field: 'student_govt_benefits.has_active_benefits',
      condition_field_2: 'student_financial.total_annual_income',
      operator: RuleOperator.AND_COMPOUND,
      default_value: { field1_eq: true, field2_gte: 500000 },
      value_type: ValueType.number, score_pts: -5.00, sort_order: 440,
      rule_description: 'Receiving BPL/AAY/MGNREGA benefits AND income  5L. Fraudulent welfare claim. 5 pts.',
      on_pass_action: 'integrity_adj += -5',
      on_fail_action: 'integrity_adj += 0',
      cross_references: 'F-01, B-01',
    },

    //  DOMAIN H  COMPOSITE COMPUTATION 
    {
      rule_code: 'H-01', rule_name: 'Merit Score Total', domain: 'H',
      rule_type: RuleType.COMPOSITE, score_bucket: ScoreBucket.merit,
      condition_field: 'computed.merit_score',
      operator: RuleOperator.FORMULA,
      default_value: { formula: 'SUM(A-01..A-10)', clamp_min: 0, clamp_max: 100 },
      value_type: ValueType.formula, score_pts: null, sort_order: 460,
      rule_description: 'Sum of all Domain A scores, clamped 0100.',
      on_pass_action: 'merit_score = clamp(sum_A, 0, 100)',
      on_fail_action: null, cross_references: 'A-01..A-10, H-05',
    },
    {
      rule_code: 'H-02', rule_name: 'Need Score Total (Rule-Based)', domain: 'H',
      rule_type: RuleType.COMPOSITE, score_bucket: ScoreBucket.need,
      condition_field: 'computed.rule_need_score',
      operator: RuleOperator.FORMULA,
      default_value: { formula: 'SUM(B+C+D+E+F)', clamp_min: 0, clamp_max: 100 },
      value_type: ValueType.formula, score_pts: null, sort_order: 470,
      rule_description: 'Sum of Domains B+C+D+E+F, clamped 0100. Raw max ~130pts before cap. This IS the final need score  no ML blend applied.',
      on_pass_action: 'rule_need_score = clamp(sum_BCDEF, 0, 100)',
      on_fail_action: null, cross_references: 'B..F rules, H-05',
    },
    {
      // H-03 DEACTIVATED  XGBoost need-score blend removed.
      // Need scoring is now 100% rule-based (H-02 feeds directly into H-05).
      // H-03 is retained in DB for audit/reference only.
      rule_code: 'H-03', rule_name: 'ML-Blended Need Score (DEACTIVATED)', domain: 'H',
      rule_type: RuleType.COMPOSITE, score_bucket: ScoreBucket.need,
      condition_field: 'computed.final_need_score',
      operator: RuleOperator.FORMULA,
      default_value: { formula: '(1-blend)*rule_need + blend*ml_need', blend: 0.0, cold_start_blend: 0.0 },
      value_type: ValueType.formula, score_pts: null, sort_order: 480,
      is_active: false,
      rule_description: 'DEACTIVATED  XGBoost ML need-score blend removed for full explainability and operational simplicity. Need scoring uses H-02 (rule_need_score) directly. Re-activate only if adding XGBoost back.',
      on_pass_action: 'n/a (deactivated)',
      on_fail_action: null, cross_references: 'H-02',
    },
    {
      rule_code: 'H-04', rule_name: 'Integrity Adjustment Total', domain: 'H',
      rule_type: RuleType.COMPOSITE, score_bucket: ScoreBucket.integrity,
      condition_field: 'computed.integrity_adj',
      operator: RuleOperator.FORMULA,
      default_value: { formula: 'SUM(G-01..G-07)', clamp_min: -40, clamp_max: 0 },
      value_type: ValueType.formula, score_pts: null, sort_order: 490,
      rule_description: 'Sum of all G-domain deductions, clamped 40 to 0.',
      on_pass_action: 'integrity_adj = clamp(sum_G, -40, 0)',
      on_fail_action: null, cross_references: 'G-01..G-07, H-05',
    },
    {
      rule_code: 'H-05', rule_name: 'COMPOSITE Score (TOPSIS)', domain: 'H',
      rule_type: RuleType.COMPOSITE, score_bucket: ScoreBucket.none,
      condition_field: 'computed.composite_score',
      operator: RuleOperator.FORMULA,
      default_value: {
        method: 'TOPSIS',
        weights: { merit: 0.35, need: 0.65 },
        normalisation: 'vector',
        integrity_as: 'direct_deduction',
        formula: 'Ci = d_minus / (d_plus + d_minus); composite = clamp(Ci * 100 + integrity_adj, 0, 100)',
        clamp_min: 0, clamp_max: 100,
      },
      value_type: ValueType.formula, score_pts: null, sort_order: 500,
      rule_description: 'TOPSIS final ranking: vector-normalises merit (w=0.35) and need (w=0.65) across the entire cohort, computes closeness coefficient Ci = d/(d+d), then composite = clamp(Ci100 + integrity_adj, 0, 100). Replaces WSM for cohort-relative fairness.',
      on_pass_action: 'composite = clamp(TOPSIS_Ci * 100 + H-04, 0, 100)',
      on_fail_action: null, cross_references: 'H-01, H-02, H-04',
    },

    //  DOMAIN I  VERIFICATION THRESHOLDS 
    {
      rule_code: 'I-01', rule_name: 'Field Verification Match Score', domain: 'I',
      rule_type: RuleType.THRESHOLD, score_bucket: ScoreBucket.none,
      condition_field: 'verifier_field_reports.match_score',
      operator: RuleOperator.FORMULA,
      default_value: { formula: 'yes_count / total_fields * 100' },
      value_type: ValueType.formula, score_pts: null, sort_order: 510,
      rule_description: 'Computed from verifier form: yes_count  total_fields  100. Input for I-02, I-03, I-04.',
      on_pass_action: 'match_score computed', on_fail_action: null,
      cross_references: 'I-02, I-03, I-04',
    },
    {
      rule_code: 'I-02', rule_name: 'Auto-Approve (High Match, Clean)', domain: 'I',
      rule_type: RuleType.THRESHOLD, score_bucket: ScoreBucket.none,
      condition_field: 'applications.verification_match_score',
      condition_field_2: 'applications.anomaly_flag',
      operator: RuleOperator.AND_COMPOUND,
      default_value: { field1_gte: 80, field2_eq: false },
      value_type: ValueType.number, score_pts: null, sort_order: 520,
      rule_description: 'Match  80% AND no anomaly flag  composite unchanged (1.0). Re-ranked for final selection.',
      on_pass_action: 'post_verify_composite = composite * 1.0',
      on_fail_action: 'route to I-03 or I-04',
      cross_references: 'I-01, I-03, I-04',
    },
    {
      rule_code: 'I-03', rule_name: 'Human Review Penalty (Mid Match / Anomaly)', domain: 'I',
      rule_type: RuleType.THRESHOLD, score_bucket: ScoreBucket.none,
      condition_field: 'applications.verification_match_score',
      operator: RuleOperator.RANGE_CHECK,
      default_value: { match_gte: 50, match_lt: 80, or_anomaly_flag: true, multiplier: 0.85 },
      value_type: ValueType.range, score_pts: null, sort_order: 530,
      rule_description: 'Match 5079%  composite  0.85.',
      on_pass_action: 'post_verify_composite = composite * 0.85',
      on_fail_action: 'route to I-04',
      cross_references: 'I-01, I-02, I-04',
    },
    {
      rule_code: 'I-04', rule_name: 'Low Match Penalty (Contradicted Data)', domain: 'I',
      rule_type: RuleType.THRESHOLD, score_bucket: ScoreBucket.none,
      condition_field: 'applications.verification_match_score',
      operator: RuleOperator.LT,
      default_value: { threshold: 50, multiplier: 0.5 },
      value_type: ValueType.number, score_pts: null, sort_order: 540,
      rule_description: 'Match < 50%  composite  0.50. Verified data severely contradicts declared data. Likely drops below rank cutoff.',
      on_pass_action: 'post_verify_composite = composite * 0.50',
      on_fail_action: null,
      cross_references: 'I-01, I-02, I-03',
    },

    //  DOMAIN J  AWARDS + CONFIG 
    {
      rule_code: 'J-01', rule_name: 'Base Award Amount', domain: 'J',
      rule_type: RuleType.AWARD, score_bucket: ScoreBucket.none,
      condition_field: null, operator: RuleOperator.CONSTANT,
      default_value: { amount: 50000 },
      value_type: ValueType.number, score_pts: null, sort_order: 550,
      rule_description: 'Base scholarship amount 50,000. Program-overridable via program_rule_overrides.',
      on_pass_action: 'award_amount = 50000',
      on_fail_action: null, cross_references: 'J-02..J-07',
    },
    {
      rule_code: 'J-02', rule_name: 'Income Band 1 Multiplier (1L)', domain: 'J',
      rule_type: RuleType.AWARD, score_bucket: ScoreBucket.none,
      condition_field: 'student_financial.total_annual_income',
      operator: RuleOperator.LTE,
      default_value: { threshold: 100000, multiplier: 1.5 },
      value_type: ValueType.number, score_pts: null, sort_order: 560,
      rule_description: 'Income  1L  award  1.50 = 75,000.',
      on_pass_action: 'award_amount *= 1.5',
      on_fail_action: 'check J-03',
      cross_references: 'J-01, J-03',
    },
    {
      rule_code: 'J-03', rule_name: 'Income Band 2 Multiplier (3L)', domain: 'J',
      rule_type: RuleType.AWARD, score_bucket: ScoreBucket.none,
      condition_field: 'student_financial.total_annual_income',
      operator: RuleOperator.LTE,
      default_value: { threshold: 300000, multiplier: 1.25 },
      value_type: ValueType.number, score_pts: null, sort_order: 570,
      rule_description: 'Income  3L  award  1.25 = 62,500.',
      on_pass_action: 'award_amount *= 1.25',
      on_fail_action: 'check J-04',
      cross_references: 'J-01, J-02, J-04',
    },
    {
      rule_code: 'J-04', rule_name: 'Income Band 3 Multiplier (5L)', domain: 'J',
      rule_type: RuleType.AWARD, score_bucket: ScoreBucket.none,
      condition_field: 'student_financial.total_annual_income',
      operator: RuleOperator.LTE,
      default_value: { threshold: 500000, multiplier: 1.0 },
      value_type: ValueType.number, score_pts: null, sort_order: 580,
      rule_description: 'Income  5L  award  1.00 = 50,000 (base).',
      on_pass_action: 'award_amount *= 1.0',
      on_fail_action: 'check J-05',
      cross_references: 'J-01, J-03, J-05',
    },
    {
      rule_code: 'J-05', rule_name: 'Income Band 4 Multiplier (8L)', domain: 'J',
      rule_type: RuleType.AWARD, score_bucket: ScoreBucket.none,
      condition_field: 'student_financial.total_annual_income',
      operator: RuleOperator.LTE,
      default_value: { threshold: 800000, multiplier: 0.75 },
      value_type: ValueType.number, score_pts: null, sort_order: 590,
      rule_description: 'Income  8L  award  0.75 = 37,500.',
      on_pass_action: 'award_amount *= 0.75',
      on_fail_action: 'award_amount = 0 (not selected or income too high)',
      cross_references: 'J-01, J-04',
    },
    {
      rule_code: 'J-06', rule_name: 'Disability Award Uplift', domain: 'J',
      rule_type: RuleType.AWARD, score_bucket: ScoreBucket.none,
      condition_field: 'student_personal.is_differently_abled',
      operator: RuleOperator.EQ,
      default_value: { value: true, additional_multiplier: 1.15 },
      value_type: ValueType.boolean, score_pts: null, sort_order: 600,
      rule_description: 'Differently-abled applicants receive additional 1.15 (+15%) on top of income band award.',
      on_pass_action: 'award_amount *= 1.15',
      on_fail_action: null,
      cross_references: 'F-02, J-01',
    },
    {
      rule_code: 'J-07', rule_name: 'Top Need Quartile Uplift', domain: 'J',
      rule_type: RuleType.AWARD, score_bucket: ScoreBucket.none,
      condition_field: 'applications.rule_need_score',
      operator: RuleOperator.RANK_CUTOFF,
      default_value: { percentile_cutoff: 75, additional_multiplier: 1.1 },
      value_type: ValueType.number, score_pts: null, sort_order: 610,
      rule_description: 'If rule_need_score in top 25% of program  additional 1.10 (+10%). Rewards highest-need approved students.',
      on_pass_action: 'award_amount *= 1.10',
      on_fail_action: null,
      cross_references: 'H-02, J-01',
    },
    {
      rule_code: 'J-08', rule_name: 'Maximum Selections Config', domain: 'J',
      rule_type: RuleType.CONFIG, score_bucket: ScoreBucket.none,
      condition_field: null, operator: RuleOperator.CONFIG,
      default_value: { seats: 100 },
      value_type: ValueType.number, score_pts: null, sort_order: 620,
      rule_description: 'Maximum approved selections per program. Default 100. Program-overridable.',
      on_pass_action: 'program.total_seats = 100',
      on_fail_action: null, cross_references: 'J-09',
    },
    {
      rule_code: 'J-09', rule_name: 'Waitlist Size Config', domain: 'J',
      rule_type: RuleType.CONFIG, score_bucket: ScoreBucket.none,
      condition_field: null, operator: RuleOperator.CONFIG,
      default_value: { waitlist_size: 20 },
      value_type: ValueType.number, score_pts: null, sort_order: 630,
      rule_description: 'Waitlist slots (ranks 101120). Activated if an approved student declines. Default 20.',
      on_pass_action: 'waitlist = ranks 101 to 120',
      on_fail_action: null, cross_references: 'J-08',
    },
  ]

  console.log(`   Inserting ${rules.length} rules...`)
  for (const rule of rules) {
    await prisma.eligibilityRule.upsert({
      where: { rule_code: rule.rule_code },
      update: rule,
      create: rule,
    })
  }

  //  SAMPLE PROGRAM 
  console.log('   Seeding sample program...')
  await prisma.scholarshipProgram.upsert({
    where: { program_code: 'SCH-2025-01' },
    update: {},
    create: {
      program_name: 'Annual Merit-cum-Need Scholarship 202526',
      program_code: 'SCH-2025-01',
      academic_year: '2025-26',
      description: 'Annual scholarship for economically disadvantaged students pursuing higher education in Tamil Nadu.',
      total_seats: 100,
      shortlist_multiplier: 2.0,
      is_active: true,
      created_by: 'system',
    },
  })

  console.log(' Seeding complete.')
  console.log(`    ${institutions.length} institutions`)
  console.log(`    3 system users (admin, officer, program manager)`)
  console.log(`    ${rules.length} eligibility rules across domains AJ`)
  console.log('    1 sample scholarship program')
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(async () => { await prisma.$disconnect() })
